networks:
  nnx:
    external: true
services:
  vue-app:
    container_name: meowmeow
    build: .
    ports:
      - "5173:5073"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - nnx
